package server

import "github.com/go-chi/chi/v5"

// mountSensitiveTokenRoutes registers everything gated behind the sensitive
// local-token guard: first-run tool installs, provider configuration and
// credential/OAuth flows, the model gateway, the plugin registry, and the
// runtime settings that change how agents execute. The guard is applied once
// to the whole group so an individual handler cannot forget it.
func (s *Server) mountSensitiveTokenRoutes(r chi.Router) {
	r.Group(func(r chi.Router) {
		r.Use(s.sensitiveLocalTokenGuard)
		r.Post("/api/setup/install", s.setupInstall)
		r.Get("/api/setup/install/status", s.setupInstallStatus)
		r.Post("/api/providers/test", s.testProviderConfigDraft)
		r.Post("/api/providers/test-message", s.testProviderMessageDraft)
		r.Put("/api/providers/{name}/config", s.updateProviderConfig)
		r.Patch("/api/providers/{name}", s.patchProviderConfig)
		r.Delete("/api/providers/{name}", s.deleteProviderConfig)
		r.Post("/api/providers/{name}/test", s.testProviderConfig)
		r.Get("/api/gateway/status", s.gatewayRuntimeStatus)
		r.Patch("/api/gateway/config", s.patchGatewayRuntimeConfig)
		r.Get("/api/gateway/accounts", s.listGatewayAccounts)
		r.Patch("/api/gateway/accounts/{provider}/{accountId}", s.patchGatewayAccount)
		r.Get("/api/gateway/requests", s.listGatewayRequests)
		r.Get("/api/gateway/keys", s.listGatewayKeys)
		r.Post("/api/gateway/keys", s.createGatewayKey)
		r.Patch("/api/gateway/keys/{id}", s.updateGatewayKey)
		r.Post("/api/gateway/keys/{id}/rotate", s.rotateGatewayKey)
		r.Post("/api/gateway/keys/{id}/revoke", s.revokeGatewayKey)
		r.Delete("/api/gateway/keys/{id}", s.deleteGatewayKey)
		r.Get("/api/gateway/models", s.listGatewayModels)
		r.Post("/api/gateway/models", s.createGatewayModel)
		r.Patch("/api/gateway/models", s.updateGatewayModel)
		r.Delete("/api/gateway/models", s.deleteGatewayModel)
		r.Patch("/api/gateway/models/{alias}", s.updateGatewayModel)
		r.Delete("/api/gateway/models/{alias}", s.deleteGatewayModel)
		r.Get("/api/gateway/usage", s.gatewayUsage)
		// The tunnel that publishes /v1 publicly. Same shape as the UI tunnel
		// endpoints; each mutating handler enforces remoteSecurityMutationAllowed
		// itself, so no extra middleware is required here.
		r.Get("/api/gateway/tunnel", s.getGatewayTunnel)
		r.Post(gatewayTunnelInstallPath, s.installGatewayTunnel)
		r.Post("/api/gateway/tunnel", s.startGatewayTunnel)
		r.Delete("/api/gateway/tunnel", s.stopGatewayTunnel)
		r.Post("/api/providers/oauth/codex/login/start", s.startCodexOAuthLogin)
		r.Get("/api/providers/oauth/codex/login/{loginId}", s.getCodexOAuthLogin)
		r.Delete("/api/providers/oauth/codex/login/{loginId}", s.cancelCodexOAuthLogin)
		r.Get("/api/providers/oauth/codex/accounts", s.listCodexOAuthAccounts)
		r.Post("/api/providers/oauth/codex/accounts/batch", s.batchCodexOAuthAccounts)
		r.Get("/api/providers/oauth/codex/accounts/{id}/export", s.exportCodexOAuthAccount)
		r.Patch("/api/providers/oauth/codex/accounts/{id}", s.patchCodexOAuthAccount)
		r.Post("/api/providers/oauth/codex/accounts/{id}/refresh", s.refreshCodexOAuthAccount)
		r.Delete("/api/providers/oauth/codex/accounts/{id}", s.deleteCodexOAuthAccount)
		r.Post("/api/providers/oauth/codex/import", s.importCodexOAuthCredentials)
		r.Post("/api/providers/oauth/codex/import/batch", s.batchImportCodexOAuthCredentials)
		r.Post("/api/providers/oauth/anthropic/login/start", s.startAnthropicOAuthLogin)
		r.Get("/api/providers/oauth/anthropic/login/{loginId}", s.getAnthropicOAuthLogin)
		r.Post("/api/providers/oauth/anthropic/login/{loginId}/submit", s.submitAnthropicOAuthLogin)
		r.Delete("/api/providers/oauth/anthropic/login/{loginId}", s.cancelAnthropicOAuthLogin)
		r.Post("/api/providers/oauth/{provider}/login/start", s.startSubscriptionOAuthLogin)
		r.Get("/api/providers/oauth/{provider}/login/{loginId}", s.getSubscriptionOAuthLogin)
		r.Delete("/api/providers/oauth/{provider}/login/{loginId}", s.cancelSubscriptionOAuthLogin)
		r.Post("/api/providers/oauth/kiro/login/{loginId}/submit", s.submitKiroOAuthLogin)
		r.Post("/api/providers/oauth/kiro/login/{loginId}/submit-apikey", s.submitKiroAPIKeyLogin)
		r.Get("/api/providers/auth/anthropic/accounts", s.listAnthropicAccounts)
		r.Post("/api/providers/auth/anthropic/accounts", s.createAnthropicAccount)
		r.Patch("/api/providers/auth/anthropic/accounts/{id}", s.patchAnthropicAccount)
		r.Post("/api/providers/auth/anthropic/accounts/{id}/sync", s.syncAnthropicAccount)
		r.Delete("/api/providers/auth/anthropic/accounts/{id}", s.deleteAnthropicAccount)
		r.Get("/api/providers/auth/{provider}/accounts", s.listSubscriptionAccounts)
		r.Patch("/api/providers/auth/{provider}/accounts/{id}", s.patchSubscriptionAccount)
		r.Post("/api/providers/auth/{provider}/accounts/{id}/sync", s.syncSubscriptionAccount)
		r.Delete("/api/providers/auth/{provider}/accounts/{id}", s.deleteSubscriptionAccount)
		r.Get("/api/providers/{name}/auth-files", s.listProviderAuthFiles)
		r.Post("/api/providers/{name}/auth-files/import", s.importProviderAuthFile)
		r.Get("/api/plugins", s.listPlugins)
		r.Post("/api/plugins/install", s.installPlugin)
		r.Get("/api/plugins/{id}", s.getPlugin)
		r.Post("/api/plugins/{id}/enable", s.enablePlugin)
		r.Post("/api/plugins/{id}/disable", s.disablePlugin)
		r.Post("/api/plugins/{id}/discover", s.discoverPlugin)
		r.Post("/api/plugins/{id}/update", s.updatePlugin)
		r.Post("/api/plugins/{id}/health", s.pluginHealth)
		r.Delete("/api/plugins/{id}", s.uninstallPlugin)
		r.Patch("/api/runtime/continuation-settings", s.continuationSettingsEndpoint)
		r.Patch("/api/runtime/background-task-settings", s.backgroundRuntimeSettingsEndpoint)
		r.Patch("/api/runtime/retry-policy-settings", s.retryPolicySettingsEndpoint)
		r.Post("/api/agents/{id}/background-tasks", s.createBackgroundTask)
		r.Post("/api/background-tasks/{taskId}/cancel", s.cancelBackgroundTask)
	})
}
