package server

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

func (s *Server) mountAgentRoutes(r chi.Router) {
	r.Route("/api/agents", s.agentRoutes)
	r.Route("/api/narrators", s.agentRoutes)
}

func (s *Server) agentRoutes(r chi.Router) {
	r.Get("/{id}", s.getAgent)
	r.Get("/{id}/live-snapshot", s.getAgentLiveSnapshot)
	r.Get("/{id}/context", s.getAgentContext)
	r.With(s.fullRemoteAccessGuard).Patch("/{id}/context/preferences", s.patchAgentContextPreferences)
	r.With(s.fullRemoteAccessGuard).Post("/{id}/context/compact", s.compactAgentContext)
	r.With(s.fullRemoteAccessGuard).Post("/{id}/context/clear", s.clearAgentContext)
	r.With(s.fullRemoteAccessGuard).Post("/{id}/context/retain", s.retainAgentContextSummary)
	r.Patch("/{id}/title", s.updateAgentTitle)
	r.Patch("/{id}/cwd", s.updateAgentCWD)
	r.Patch("/{id}/model", s.updateAgentModel)
	r.Patch("/{id}/reasoning-effort", s.updateAgentReasoningEffort)
	r.Patch("/{id}/fast-mode", s.updateAgentFastMode)
	r.Patch("/{id}/permission-mode", s.updateAgentPermissionMode)
	r.Patch("/{id}/plan-mode", s.updateAgentPlanMode)
	r.Patch("/{id}/navigation-state", s.patchAgentNavigationState)
	r.With(s.fullRemoteAccessGuard).Delete("/{id}", s.deleteArchivedAgent)
	r.Get("/{id}/plans", s.listReviewPlans)
	r.Post("/{id}/plans", s.createReviewPlan)
	r.Get("/{id}/plans/{planId}", s.getReviewPlan)
	r.Post("/{id}/plans/{planId}/approve", s.approveReviewPlan)
	r.Post("/{id}/plans/{planId}/execute", s.executeReviewPlan)
	r.Post("/{id}/plans/{planId}/cancel", s.cancelReviewPlan)
	r.Post("/{id}/plans/{planId}/replan", s.replanReviewPlan)
	r.Post("/{id}/interrupt", s.interruptAgent)
	r.Get("/{id}/messages", s.listMessages)
	r.Post("/{id}/messages", s.postMessage)
	r.Get("/{id}/draft", s.getMessageDraft)
	r.Put("/{id}/draft", s.putMessageDraft)
	r.Delete("/{id}/draft", s.deleteMessageDraft)
	r.Get("/{id}/queue", s.listQueuedMessages)
	r.Post("/{id}/queue", s.enqueueMessage)
	r.Put("/{id}/queue/{queueId}", s.updateQueuedMessage)
	r.Delete("/{id}/queue/{queueId}", s.deleteQueuedMessage)
	r.Post("/{id}/messages/{messageId}/corrections", s.createCorrection)
	r.Post("/{id}/messages/{messageId}/rerun", s.rerunMessage)
	r.With(s.fullRemoteAccessGuard).Post("/{id}/messages/{messageId}/rollback", s.rollbackConversationToMessage)
	r.With(s.fullRemoteAccessGuard).Post("/{id}/messages/{messageId}/fork", s.forkConversationFromMessage)
	r.With(s.fullRemoteAccessGuard).Delete("/{id}/messages/{messageId}", s.deleteConversationMessage)
	r.Get("/{id}/messages/{messageId}/attachments/{attachmentId}", s.getMessageAttachment)
	r.Get("/{id}/messages/{messageId}/generated-images/{assetId}", s.getGeneratedImage)
	r.MethodFunc(http.MethodHead, "/{id}/messages/{messageId}/generated-images/{assetId}", s.getGeneratedImage)
	r.Get("/{id}/runs", s.listRuns)
	r.Get("/{id}/runs/active", s.getActiveRunSummary)
	r.Get("/{id}/runs/{runId}", s.getRunSummary)
	r.Get("/{id}/runs/{runId}/rollback", s.rollbackRunPreview)
	r.Post("/{id}/runs/{runId}/rollback", s.rollbackRun)
	r.Get("/{id}/runs/{runId}/tool-calls", s.listRunToolCalls)
	r.Get("/{id}/background-tasks", s.listBackgroundTasks)
	r.Get("/{id}/tools", s.listTools)
	r.Post("/{id}/tool-calls", s.executeTool)
	r.Get("/{id}/tool-calls/pending", s.listPendingToolCalls)
	r.Post("/{id}/tool-calls/{toolUseId}/approval", s.approveToolCall)
	r.Post("/{id}/tool-calls/{toolUseId}/user-answer", s.answerUserQuestion)
	r.Get("/{id}/tool-calls/{toolUseId}", s.getToolCall)
	r.Get("/{id}/git/status", s.gitStatus)
	r.Get("/{id}/git/diff", s.gitDiff)
	r.Get("/{id}/git/log", s.gitLog)
	r.Post("/{id}/git/commit", s.gitCommit)
	r.Post("/{id}/git/discard", s.gitDiscard)
	r.Get("/{id}/workspace/tree", s.workspaceTree)
	r.Get("/{id}/workspace/file", s.workspaceFile)
	r.Put("/{id}/workspace/file", s.updateWorkspaceFile)
	r.Get("/{id}/preview/detect", s.detectPreview)
	r.Post("/{id}/preview/start", s.startPreview)
	r.Post("/{id}/preview/stop", s.stopPreview)
	r.Get("/{id}/preview/status", s.previewStatus)
	r.Get("/{id}/preview/logs", s.previewLogs)
}
